### PR TITLE
Update AMDGPU test to 0.5

### PR DESCRIPTION
**Pull request by luraess**
Modify sync function.

Other infos:
- Since AMDGPU v0.5, we no longer use HSA but HIP as backend. This makes the low-level AMDGPU API much closer to CUDA but introduces breaking changes.
- Also, AMDGPU currently only works properly with Julia 1.9

Given the ☝️, tests should rather only support AMDGPU >= 0.5 and Julia 1.9. For MPI.jl, I don't know how to handle it. I'd lean towards restricting the usage of AMDGPU Ext to Julia 1.9, AMDGPU 0.5...

### CODE REVIEW

**Comment by luraess** [comment]
@giordano don't know why the history stills shows up here. Sorry.

**Comment by giordano** [comment]
Maybe because you just branched out from your already borked `master` branch, instead of `origin/master`.  You should never do local changes to your `master` branch for this reason, all branches will be messed up.

**Comment by luraess** [comment]
Let me try fixing this then.

**Comment by luraess** [comment]
Should be good now in #755

**Pull request closed without merging**
