### PR TITLE
Use consts for known ABIs

### PR DESCRIPTION
**Pull request by simonbyrne**
Adds a mechanism to detect the ABI via MPI_LIBRARY_VERSION_STRING, and use that to detect the appropriate consts file, falling back on the C generator only when that fails.

### CODE REVIEW

**Comment by simonbyrne** [comment]
@vchuravy or @leios: can you try this out on Spectrum MPI? I don't know if the constants are the same as OpenMPI or not.

**Comment by simonbyrne** [comment]
Note that this disables the automatic `--oversubscribe` for OpenMPI tests: you can however set the environment variable `JULIA_MPIEXEC_ARGS="--oversubscribe"`

**Comment by simonbyrne** [comment]
@leios What does
```
MPI.MPI_LIBRARY
MPI.MPI_LIBRARY_VERSION
MPI.MPI_LIBRARY_ABI
```
give?

**Comment by leios** [comment]
```
julia> MPI.MPI_LIBRARY_ABI
OpenMPIABI::MPIABI = 2

julia> MPI.MPI_LIBRARY_VERSION
v"10.3.0"

julia> MPI.MPI_LIBRARY
IBMSpectrumMPI::MPIImpl = 5
```

**Pull request merged**
