### PR TITLE
Consistently use `Base.julia_cmd()` in tests

### PR DESCRIPTION
**Pull request by giordano**
This should in principle avoid running in https://github.com/JuliaLang/julia/issues/48039, but locally I'm still seeing the same problem :confused:

### CODE REVIEW

**Comment by KristofferC** [comment]
Pkg.develop should already run the auto precompilation unless that is explicitly disabled somewhere else.

**Comment by giordano** [comment]
Without `Pkg.precompile` I get
```
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for MPI [da04e1cc-30fd-572f-bb4f-1f8673147195]
│   exception = Required dependency DocStringExtensions [ffbed154-4ef7-542d-bbb7-c09d3a79fcae] failed to load from a cache file.
└ @ Base loading.jl:1675
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for MPI [da04e1cc-30fd-572f-bb4f-1f8673147195]
│   exception = Required dependency DocStringExtensions [ffbed154-4ef7-542d-bbb7-c09d3a79fcae] failed to load from a cache file.
└ @ Base loading.jl:1675
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for MPI [da04e1cc-30fd-572f-bb4f-1f8673147195]
│   exception = Invalid input in module list: expected DocStringExtensions.
└ @ Base loading.jl:1675
```

**Comment by KristofferC** [comment]
Maybe the auto precompile doesn't run on CI or something.

**Comment by giordano** [comment]
This seems to be working?  The [failure](https://github.com/JuliaParallel/MPI.jl/actions/runs/3911362636/jobs/6684671575) in `test-openmpi-jll (macos-latest, nightly, x64)` looks unrelated to caching problem.

@vchuravy my understanding is that using `Base.julia_exename()` instead of `Base.julia_cmd()` increases the likelihood of rejecting cache because different flags are more important now.  Luckily, for the other tests we are already using `Base.julia_cmd`: https://github.com/JuliaParallel/MPI.jl/blob/06b16fc4814732c83f7d58550142b56e9e1f3472/test/runtests.jl#L47 (introduced by https://github.com/JuliaParallel/MPI.jl/commit/3e52a3a8232e67422ded1cd9c5e4df559358f184).  Does this make sense?

**Comment by vchuravy** [comment]
Yeah that makes sense we create the cachefiles with different flags.

**Comment by IanButterworth** [comment]
`Pkg.dev` never autoprecompiles

**Comment by giordano** [comment]
Alright, using `Base.julia_cmd()` also in `test/test_spawn.jl` fixed the remaining failures, now all the nightly tests are green :partying_face:   I'll clean up this PR to revert  the extra commits and merge it.

**Pull request merged**
