### PR TITLE
RFC: Implement many of the MPI functions

### PR DESCRIPTION
**Pull request by kshyatt**
Added wrappers and some tests for:
- `MPI_Scatter`
- `MPI_Scatterv`
- `MPI_Gather`
- `MPI_Gatherv`
- `MPI_Allgather`
- `MPI_Allgatherv`
- `MPI_Alltoall`
- `MPI_Alltoallv`
- `MPI_Scan`
- `MPI_Exscan`

I'd be happy to write more tests if the ones I have so far are insufficient.

### CODE REVIEW

**Comment by ViralBShah** [comment]
+1 for these wrappers!

**Comment by lcw** [comment]
These look great.  Thanks for the code.

**Comment by kshyatt** [comment]
Cheers. Are there other functions that are high priority to wrap? I held off on touching the whole File/IO part of the API because @timholy and @tkelman have been after me to wrap Parallel HDF5 instead.

**Comment by lcw** [comment]
I would suggest adding stuff that is interesting to you.  I am pretty
open.

I am mainly a MPI 1 kind of guy myself.  So I would like to make sure it
is wrapped first, but many people might find MPI IO interesting as well.
One thing we do want is to make sure any MPI 3 functionality is
optional.  Not everyone will have access to MPI 3 libraries.

One thing that I think needs to be fixed, which I am not sure exactly
how it should be done, is the possibly problematic use of buffers in
[`isend`][1].  As far as I can tell `buf` in `isend` may not actually
survive tell when it is needed if the garbage collector kicks in.

You can also see that [`irecv`][2] doesn't actually perform a nonblocking
receive.  I am not sure if there is anything that can be done there.

Have you checked out [ADIOS][3]?  I am planning on using it for large
scale parallel IO in my current project.  It is a wrapper library that
can call many different backends for IO (e.g., POSIX IO, MPI IO, HDF5,
...).  Is has asynchronous IO which I think is interesting.  It would be
cool to see if we can get that to work with MPI.jl.


[1] https://github.com/JuliaParallel/MPI.jl/blob/188e3c2af107ff51900e09e71acd14b77833cef5/src/mpi-base.jl#L189-L192
[2] https://github.com/JuliaParallel/MPI.jl/blob/188e3c2af107ff51900e09e71acd14b77833cef5/src/mpi-base.jl#L238-L247
[3] https://www.olcf.ornl.gov/center-projects/adios/

**Comment by timholy** [comment]
No pressure from me :smile:, you should do what you think best.

**Comment by lcw** [comment]
It would be interesting to see how MPI.jl interacts with existing MPI libraries such as Parallel HDF5, PETSc, or Trilinos (with Cxx.jl).

**Comment by tkelman** [comment]
I agree that seeing if MPI.jl can make it easier to leverage the huge body of existing HPC libraries would be really interesting to me, as a greedy person. But I'm with @timholy, you should work on whatever maximizes your own personal excitement.

**Comment by kshyatt** [comment]
:laughing: I asked because I don't have anything super-exciting lined up, and I'm avoiding HDF5!

**Comment by psanan** [comment]
I'm interested in helping out with efforts to provide a wrapper for PETSc.

**Comment by timholy** [comment]
Oh, yes, then by all means please do use me as an excuse!

**Comment by eschnett** [comment]
@lcw `isend` does not protect the buffer from garbage collection, but the buffer is stored in the request object that is created. This request object is needed to check whether the communication has finished. It is conceivable that a user discards the request object, which then leads to a segfault -- but this is an error anyway, as it would be a resource leak in MPI.

`irecv` performs a non-blocking read, but only if a non-blocking probe determined that a message is available. I've read somewhere (can't recall where) that this is safe to do, unless another, concurrent MPI call accepts this message first. The latter would be a problem even if we used a non-blocking receive here, since -- if the message is no longer available -- this receive may never finish.

**Comment by lcw** [comment]
@eschnett Oh very good.  I missed the buffer being placed into the
Request.  I guess it is a non issue.

**Pull request merged**
