### PR TITLE
test Julia 1.4, remove 1.1 & 1.2 from CI matrix

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by simonbyrne** [comment]
Hmm, bizarre failure in `test_threads.jl`:
```
signal (4): Illegal instruction: 4

in expression starting at /Users/travis/build/JuliaParallel/MPI.jl/test/test_threads.jl:42

_os_unfair_lock_recursive_abort at /usr/lib/system/libsystem_platform.dylib (unknown line)

_os_unfair_lock_lock_slow at /usr/lib/system/libsystem_platform.dylib (unknown line)

pthread_rwlock_destroy at /usr/lib/system/libsystem_pthread.dylib (unknown line)

pmix_ds12_lock_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/pmix/mca_gds_ds12.so (unknown line)

_esh_session_release at /usr/local/Cellar/open-mpi/4.0.3/lib/libmca_common_dstore.1.dylib (unknown line)

pmix_common_dstor_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/libmca_common_dstore.1.dylib (unknown line)

pmix_gds_close at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_pmix_pmix3x.so (unknown line)

OPAL_MCA_PMIX3X_pmix_mca_base_framework_close at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_pmix_pmix3x.so (unknown line)

OPAL_MCA_PMIX3X_pmix_rte_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_pmix_pmix3x.so (unknown line)

OPAL_MCA_PMIX3X_PMIx_Finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_pmix_pmix3x.so (unknown line)

pmix3x_client_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_pmix_pmix3x.so (unknown line)

rte_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/openmpi/mca_ess_pmi.so (unknown line)

orte_finalize at /usr/local/Cellar/open-mpi/4.0.3/lib/libopen-rte.40.dylib (unknown line)

ompi_mpi_finalize at /usr/local/lib/libmpi.dylib (unknown line)

_Finalize at /Users/travis/build/JuliaParallel/MPI.jl/src/environment.jl:206 [inlined]

refcount_dec at /Users/travis/build/JuliaParallel/MPI.jl/src/environment.jl:27 [inlined]

Finalize at /Users/travis/build/JuliaParallel/MPI.jl/src/environment.jl:202

unknown function (ip: 0x112467961)

jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]

do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:328

eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0

jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:888

unknown function (ip: 0xfffffffffffffffe)

unknown function (ip: 0x11d0d8a0f)

unknown function (ip: 0x0)

jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:897

jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:814

jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:873

jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:878 [inlined]

jl_load_ at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:885

include at ./boot.jl:328 [inlined]

include_relative at ./loading.jl:1105

include at ./Base.jl:31

exec_options at ./client.jl:287

_start at ./client.jl:460

jfptr__start_2084.clone_1 at /Users/travis/julia/lib/julia/sys.dylib (unknown line)

true_main at /Users/travis/julia/bin/julia (unknown line)

main at /Users/travis/julia/bin/julia (unknown line)

Allocations: 2531110 (Pool: 2530578; Big: 532); GC: 2

--------------------------------------------------------------------------

Primary job  terminated normally, but 1 process returned

a non-zero exit code. Per user-direction, the job has been aborted.

--------------------------------------------------------------------------

--------------------------------------------------------------------------

mpiexec noticed that process rank 1 with PID 0 on node Traviss-Mac-6 exited on signal 4 (Illegal instruction: 4).

--------------------------------------------------------------------------

[Traviss-Mac-6.local:49480] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

ERROR: LoadError: failed process: Process(`mpiexec --oversubscribe -n 2 /Users/travis/julia/bin/julia --code-coverage=user /Users/travis/build/JuliaParallel/MPI.jl/test/test_threads.jl`, ProcessExited(132)) [132]

```

**Comment by simonbyrne** [comment]
This might be related to https://github.com/open-mpi/ompi/issues/7516.

**Comment by simonbyrne** [comment]
@vchuravy @maleadt : how do I update the GitLab CI to the latest version?

**Comment by maleadt** [comment]
You're using an old template, we're at v6.yml and don't maintain the Docker images anymore. For example: https://github.com/JuliaGPU/CUDAnative.jl/blob/v2.10.2/.gitlab-ci.yml (if you're using latest CUDnative/CuArrays, you can check out the master branch of that file, where regular Ubuntu images are used in combination with artifacts).

**Comment by simonbyrne** [comment]
Thanks @maleadt, I was able to get it to work.

**Pull request merged**
