### PR TITLE
simplify test/wait

### PR DESCRIPTION
**Pull request by simonbyrne**
This simplifies `MPI.TestX` and `MPI.WaitX`:
1. they only return a single argument
2. `MPI.RequestSet` object to reduce allocations in `[Test|Wait][All|Any|Some]`
3. remove `!` from name.
4. if you require `Status` objects, `Array{Status}` or `Ref{Status}` have to be passed as extra arguments

This supercedes #295, and supplements #452.

The change in 4 could be applied to other functions, though it gets more difficult to deprecate those cleanly since they won't be renamed:
- `Recv`
- `Recv!`
- `recv`
- `Probe`
- `Iprobe`

### CODE REVIEW

**Comment by eschnett** [comment]
This package offers two APIs, a low-level and a high-level one.

- Typically, the low-level API uses names and arguments that closely follow the MPI standard, e.g. `Send` (with an upper case `S`) and explicit buffer management.
- The high-level API uses lower case letters (e.g. `send`), as is common in Julia, and often has a more comfortable calling behaviour.

I would not remove the low-level API. I would un-deprecate `Init_threads`, and keep `Wait`, `Test` etc. around, with all their versions. Since they modify their request argument, they have an exclamation mark in their name. This low-level API is there so that newcomers can quickly program with MPI in Julia, easily e.g. translating C/C++/Fortran/Python code, without having to learn a lot. It's also an easy base for the high-level API.

There could be new functions `wait`, `test` etc. that are much more comfortable to use. I would have called the recently introduced extended `Init` `init`, with a lower case initial letter. Ideally, one should be able to use `MPI.jl` without ever using the low-level API.

The decision to have two API levels is debatable, of course. This originally followed ideas found in `mpi4py`, many years ago. I think it's nice to have a low-level API, but with a good high-level API, the low-level API could remain unexported by default.

In the long term, I wish the blocking/non-blocking MPI calls were integrated with Julia's tasking (or even threading?) system, like regular I/O calls. `send` and `recv` would return `Task` objects, and none of the `Send/ISend/Ssend/BSend/Test/Wait/Probe/Cancel` nonsense would be necessary. If there are no Julia mechanism to work with large set of tasks (`WaitAny`, `WaitAll`, `WaitSome`), then they could be introduced.

**Comment by simonbyrne** [comment]
> This package offers two APIs, a low-level and a high-level one.
> 
>    * Typically, the low-level API uses names and arguments that closely follow the MPI standard, e.g. `Send` (with an upper case `S`) and explicit buffer management.
> 
>    * The high-level API uses lower case letters (e.g. `send`), as is common in Julia, and often has a more comfortable calling behaviour.

This isn't really true: the actual distinction is that the lowercase ones handle serialization (so that you can pass arbitrary Julia objects), the uppercase ones don't. As a result, the uppercase ones are somewhat closer to the C MPI ones, but they still differ a bit: e.g. they have a single `buffer` argument, rather than separate (pointer, len, datatype) args. Most code in the wild seems to use the uppercase ones to avoid serialization overhead.

While I would be happy to have a low-level vs high-level distinction, it would be a fair bit of work to figure out what would fall where.

> Since they modify their request argument, they have an exclamation mark in their name. 

I actually don't care that much about the suffix (though I view `MPI.Request` as similar to a `IO` or `Task` object, in that of course the argument gets modified, so the suffix is redundant). My main motivation was to simplify the cumbersome return values, and avoid the allocation of an array of `MPI.Status` objects in `Waitall!` (which most people don't care about): since this was an API break, it made sense to rename the function.

> There could be new functions `wait`, `test` etc. that are much more comfortable to use. 

I didn't want to call it `wait`, as it acts distinct from `Base.wait` (it won't `yield` to other tasks, hence #452).

> I would have called the recently introduced extended `Init` `init`, with a lower case initial letter.

I'm not opposed to this: currently `Init` does a few extra things from `MPI_Init`:

1. can safely be called multiple times (#484)
2. combines functionality from `MPI_Init_thread` (and sets a serialized as the default level)
3. attaches `MPI.Finalize` as an `atexit` hook
4. runs the init hooks (e.g. loads datatypes)
5. modifies the default error handler (to give nicer error messages)
6. checks that it is using the correct MPI launcher & library combination.

Which of these should go into `init` and which should stay in `Init`/`Init_thread`?

> In the long term, I wish the blocking/non-blocking MPI calls were integrated with Julia's tasking (or even threading?) system, like regular I/O calls. 

We can only dream...

**Comment by simonbyrne** [comment]
I've pushed the changes: I think I'd prefer to make the `Status` opt-in, since most code doesn't seem to make use of the Status objects.

I'm going to make a similar change to `Recv!`/`recv`: this will be a bit harder to deprecate, but I think we can use a similar approach.

**Comment by simonbyrne** [comment]
> I'm going to make a similar change to `Recv!`/`recv`: this will be a bit harder to deprecate, but I think we can use a similar approach.

The deprecation is a bit annoying, but I think if we add in the keyword changes in https://github.com/JuliaParallel/MPI.jl/issues/423#issuecomment-907702464, it should then only require a single change.

**Pull request merged**
