### PR TITLE
Clean up Monte Carlo example

### PR DESCRIPTION
**Pull request by eschnett**
Rename implementation source file.
Use Int instead of Float64 in various places.
Increase number of iterations.

### CODE REVIEW

**Comment by mcreel** [comment]
That wasn't much time for comments! I think that renaming montecarlo.jl is not a good idea, as montecarlo.jl has nothing to do with the implementation of computing pi - it is a general purpose function that will perform Monte Carlo of any user specified function, and will monitor the results in the way the user specifies. Calling it 07-pi-impl.jl is does not describe what the function does, in any way, and it makes it very unlikely that a user who might find the function useful will ever discover its existence.

As an example of the general purpose nature of montecarlo.jl, see https://github.com/mcreel/QuantileIV.jl/blob/master/QIVMC.jl

**Comment by andreasnoack** [comment]
Yes. I agree in both points made here by @mcreel. Please wait 24 hours before merging a pr unless it is a very simple bugfix.

**Comment by eschnett** [comment]
@mcreel Thanks for your comment. I didn't think this part of my change was controversial, otherwise I would have waited. I mainly tried to follow the naming conventions of the other files in the directory, and I tried to indicate that this file (montecarlo.jl) can't be run on its own, but rather requires a driver.

What about renaming `07-pi-impl.jl` (the previous `montecarlo.jl`) to `07-montecarlo-impl.jl`, and `07-pi.jl` to `07-pi-montecarlo.jl`?

**Comment by mcreel** [comment]
Hi Erik,
No problem. I think that the name montecarlo.jl is better. The numbers
serve to indicate what's an example. The file under discussion is not an
example. Perhaps the examples directory is not the best place for it, but I
think that the name is appropriate. The more complicated name with a number
makes it less likely that a user will discover a potentially useful
function. I don't have any preferences regarding the name of the other file.
Cheers,
M.

**Comment by eschnett** [comment]
This is now PR #102.

**Pull request merged**
