### PR TITLE
add basic error handler functionality

### LINKED ISSUE #453: Support for error handlers
It looks like MPI as early as 3.0 has error handling and it would be really awesome to have this supported in MPI.jl.

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #453.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Note that mpi4py sets `MPI_ERRORS_RETURN` on the default communicators:
https://mpi4py.readthedocs.io/en/stable/overview.html#error-handling

**Comment by simonbyrne** [comment]
@kpamnany @vchuravy any thoughts on this?

**Comment by vchuravy** [comment]
So this will no longer kill the process on error? That seems sensible, altough you could still end up in a deadlock.

**Comment by simonbyrne** [comment]
> So this will no longer kill the process on error? That seems sensible, altough you could still end up in a deadlock.

Yes, it will throw an `MPIError` instead.

**Pull request merged**
