### PR TITLE
Add Win_allocate_shared and Win_shared_query

### PR DESCRIPTION
**Pull request by JobJob**
Enables creating shared memory arrays using MPI. See tests for usage example.

### CODE REVIEW

**Comment by JobJob** [comment]
Re Win32 test errors: it wasn't me... 
It says it was test_allreduce.
All other builds are passing.

**Comment by JobJob** [comment]
Thanks folks!
> Out of interest, what is your use case for this?

I'm doing some distributed optimisation: on each node I have a master updating parameters in shared memory for workers, who then evaluate a fitness function using those parameters.

I'm hoping to release a package at some point with some tools to make this easier (pointers to related packages appreciated). While we're here: does anyone know if taking a view of an `Array{Float64,N}` is threadsafe? I can imagine it modifying some state to avoid the source array being garbage collected, and that that possibly could be an issue.

**Comment by barche** [comment]
Well, you might want to look at my [MPIArrays.jl](https://github.com/barche/MPIArrays.jl) package, I gave a talk about it at JuliaCon,but I haven't gotten round yet to releasing it officially. Seems like using `Win_allocate_shared` would also be useful there, for intra-node communication.

**Comment by JobJob** [comment]
> Well, you might want to look at my MPIArrays.jl package, I gave a talk about it at JuliaCon...

Looks cool. I'll have to watch the talk.

> Seems like using Win_allocate_shared would also be useful there, for intra-node communication.

Yeah might well be.

**Pull request merged**
