### PR TITLE
Make the tests runnable with Pkg.test()

### PR DESCRIPTION
**Pull request by ViralBShah**
I brought this up in #28, but started implementing myself. It is nice to be able to run the tests with Pkg.test(). Currently, this requires

mpirun -np <np> julia runtests.jl

Eventually, we can move to the MPIManager so that mpirun is also not necessary.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@lcw I suspect this does not work well with the tests that are part of build.jl. Would love to hear thoughts on how to streamline this, so that tests can be decoupled from the build.

**Comment by lcw** [comment]
With this patch how do you run the tests on say 5 MPI processes?
Are you thinking something like:
```
mpirun -np 5 julia -e Pkg.test("MPI")
```

This patch currently kills the testing done in CMake so that will have to be updated.

**Comment by ViralBShah** [comment]
I will update to fix the CMake tests too. I think this patch really has to use the MPIManager, so that tests can be carried out with just `Pkg.test()`.

**Comment by jakebolewski** [comment]
This has been implemented a bit differently, I think it is best to test the bindings in isolation separate from the ClusterManager interface for now to wait on that maturing a bit.

**Pull request closed without merging**
