### PR TITLE
RFC: Use C API and drop deps

### PR DESCRIPTION
**Pull request by andreasnoack**
This PR has two components.
1. It changes MPI.jl from using the Fortran API to the C API
2. It removes the deps folder and all the functionality there

I don't know if we want to do this but tests pass now so I thought it was a good time for some feedback. Part 1 is pretty simple and self explanatory. Part 2 probably requires more comments. When working in cluster environments, I've several times had issues with getting Cmake to detect MPI correctly. The number of MPI implementations is fairly small so I thought that it would be feasible to just query the MPI implementation and keep the relevant definitions types, operators etc. in Julia source files. We are already doing that Microsoft MPI and it was not that much work to cover OpenMPI and MPICH. If we continue along this path, I'll add Intel as well.

There is a challenge with respect to changes to these values within an implementation. In particular, it appears that MPICH is a little bit of an issue. In MPICH 3.0.x, the size of the `MPI_Status` struct can be set by arguments to `configure`. I try to search for the relevant arguments and, for now, throw an error if that is the case. In MPICH 3.1.x the struct is fixed size so that is simpler. The version can easily be queried so that is not really a challenge.

I'm not really sure which consequences a change like this would have on more exotic HPC systems since I don't have access to such systems. Could it work?

Finally, I've removed precompilation. I (think I) can add it back but I'm actually not sure we want it. The reason is that I've had several issues with precompilation in cluster environments with shared file system. On my machine, loading MPI takes about 0.3 seconds longer without precompilation so I think the costs are insignificant in a parallel computing setting.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I should mention that I also think it's simpler to wrap new MPI functions with the approach here since it's just a matter of using the symbol in a `ccall`. No need to modify a C source file.

Regarding the error of Windows 32 bit then I'm able to reproduce it locally although it looks different. Locally, I'm receiving a `EXCEPTION_ACCESS_VIOLATION` but on 32 bit Windows and only on release, not master, so I'm not sure it worth bothering anybody with that error. @davidanthoff is the 32 bit Windows binary relevant?

**Comment by eschnett** [comment]
The approach should work in principle. In particular, if it is better documented than the current approach, it should work better. Avoiding cmake and a Fortran compiler is a bonus. I say we test this a bit further. I would wait with merging until after 0.5 has been released, so that we don't get into two kinds of trouble at the same time.

Regarding details of `MPI_Status`: Maybe this can also be detected at run time? Allocate a sufficiently large buffer, call a respective MPI function (e.g. a self-communication), then see which parts of the buffer were modified?

The most exotic HPC system is probably Cray. Their MPI implementation is based on MPICH (?), so that should work. Apart from Intel, MVAPICH is also missing from the list, but that could also be added. I think we should add Travis test matrix elements for all supported MPI implementations.

Regarding precompiling: I think not precompiling MPI prevents any package that uses MPI from precompiling. If I recall, that was the argument for adding precompiling in the first place. (I don't understand the need to precompile -- doesn't Julia have a cache that would hold precompiled code anyway? Shouldn't thus running the test cases be almost equivalent to precompiling?)

**Comment by vchuravy** [comment]
This makes it much easier to get MPI.jl to get working in cluster environments where cmake can be tricky.

**Comment by davidanthoff** [comment]
I have a hard time imagining anyone running things on 32-bit Windows, but who knows... Do you get that error when you run julia 32 bit on 64 bit Windows, or do you also have to be on 32 bit windows?

**Comment by andreasnoack** [comment]
The error is on 32 bit Julia on 64 bit Windows. I don't have a 32 bit Windows handy.

**Comment by davidanthoff** [comment]
My vote is to ignore it... Especially if this is a julia 0.4 problem only.

**Comment by eschnett** [comment]
If we ignore this, then we should make the respective change to the Appveyor configuration, and add a comment there that 32-bit WIndows is unsupported.

**Comment by andreasnoack** [comment]
0.5 has been out for a while now so I think it's time to revisit this. I think the main issue is precompilation. I looked at it and it will require quite a bit of restructuring to get precompilation working but it should be possible. The only registered dependent package is HPAT.jl which is not precompiled so right now the need for precompilation of MPI.jl is not imminent. I think it's good to make this transition sooner than later so since it will take quite a bit of work to enable precompliation I'll suggest that we merge this without and then start working on precompilation in a separate PR. Since I opened this PR I've gotten access to a Cray system so I'll try to see if this approach works on such a system.

**Comment by vchuravy** [comment]
I am definitely in favour of merging this. I don't have any problems with dropping win32 support, but in theory you could use rdp to go onto the AppVeyor build box.

**Comment by JaredCrean2** [comment]
I think this is an improvement over the current state, but I'm a bit worried about how much work it will be to add a new MPI implementation.  Getting the values for all the constants and the sizes of structs requires could be quite difficult (I've look through `mpi.h` for MPICH, and its a mess).  Could we modify the current method to auto-generate these things, but only as a last resort (ie. if the MPI implementation is unrecognized)?

**Comment by barche** [comment]
I think switching to the C API is a great idea, it certainly simplifies adding new methods. Would it be possible to generate the implementation-specific files using Clang.jl?

Also, with 0.7 coming up, a lot of the `&` syntax in the Fortran calls needs updating, so maybe this is a goot time to bite the bullet and move to pure C.

**Comment by andreasnoack** [comment]
Things unfortunately showed up to be harder than I had imagined. MPICH has had a habit of changing their structs between minor releases in incompatible ways. Furthermore, they thought it was a great idea to make the field sizes in some of the structs configurable so basically, we won't know the sizes. Hence, I don't think we can avoid parsing the headers of the specific install of MPI. I, therefore, think that this PR would have to be split in two.

**Comment by jeffhammond** [comment]
@andreasnoack I am curious when you saw MPICH thrash ABI.  Per https://www.mpich.org/abi/, the ABI has been completely stable for more than 5 years.

**Comment by simonbyrne** [comment]
@jeffhammond This PR was opened 4 years ago: now that most implementations are standardized, I was hoping to pick up where this left off.

**Comment by andreasnoack** [comment]
@jeffhammond It's been a while so I don't remember all the details but I think I tested this on a cluster where the available version of MPICH was 3.0.x. I wasn't aware of the ABI Compatibility Initiative. That's great.

**Pull request closed without merging**
