### PR TITLE
Hotfix: Run failing `macos-latest` tests on `macos-13`

### PR DESCRIPTION
**Pull request by sloede**
Based on reports in #828

### CODE REVIEW

**Comment by sloede** [comment]
The two system/Homebrew tests on `macos-latest` fail as well:
* [`test-system-brew (mpich, 1, macos-latest)`](https://github.com/JuliaParallel/MPI.jl/actions/runs/8857338317/job/24324703125?pr=829)
* [`test-system-brew (openmpi, 1, macos-latest)`](https://github.com/JuliaParallel/MPI.jl/actions/runs/8857338317/job/24324703957?pr=829)

Switching them to `macos-13` or `macos-12` seems like a suitable workaround.

Running some more tests to see if [`test-mpitrampoline-jll (macos-latest, mpitrampoline, 1.6, x64)`](https://github.com/JuliaParallel/MPI.jl/actions/runs/8857338317/job/24324700762?pr=829) can be fixed by either going to an older macOS image or by providing the correct architecture.

**Comment by sloede** [comment]
@giordano @simonbyrne This PR provides a hotfix for the failing CI tests. Whether to merge this or not, I'll leave up to you. Unfortunately, I do not have the resources to tackle this issue at the root, so this is only a bandaid.

**Comment by giordano** [comment]
I think the problem is relatively simple: julia just can't find the MPI library because it isn't anywhere accessible.  If I manually set `DYLD_FALLBACK_LIBRARY_PATH` then I can find `libmpi`:
```
$ DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/Cellar/mpich/4.2.1/lib julia -q
julia> using Libdl

julia> find_library("libmpi")
"libmpi"
```
I have no clue of how this magically works in older versions of macOS

**Comment by giordano** [comment]
Ah, I think I understand now: up to the `macos-13` image, the `brew` commands used to install packages in `/usr/local` (which is probably a default search path for the dynamic loader), but in `macos-14` they're now installed under `/opt/homebrew`.  I don't know whether this is a change in Homebrew, or macOS, or whatever, but the net result is that `libmpi` isn't anymore in a default search path for the dynamic loader, and so we have to do something #831 to reliably make loading libmpi.  An alternative could be to tell Homebrew to install the packages again in `/usr/local`, but I think setting `DYLD_FALLBACK_LIBRARY_PATH` is slightly more general: we don't have to change the installation directory.

**Comment by sloede** [comment]
> I don't know whether this is a change in Homebrew, or macOS, or whatever

https://apple.stackexchange.com/a/437622

**Comment by giordano** [comment]
Thanks for finding the reference!  That confirms there isn't anything broken in `MPI.jl`, it was only an infrastructure change in the environment :slightly_smiling_face:

**Pull request closed without merging**
