### PR TITLE
Add one-sided communcation calls

### PR DESCRIPTION
**Pull request by barche**
This adds some of the MPI window-based (RMA) communication primitives, as well as `MPI_COMM_SPAWN`.

### CODE REVIEW

**Comment by barche** [comment]
OK, I updated this PR to just add some small fixes and the new MPI functions. Maybe it's best if I make the second PR after this one gets merged?

**Comment by vchuravy** [comment]
Thank you. Travis seems to encounter several problems.

Linux mpich:
```
signal (11): Segmentation fault
while loading /home/travis/.julia/v0.6/MPI/test/test_onesided.jl, in expression starting on line 59
unknown function (ip: 0x7f2fd9694c1c)
MPIDI_Fetch_and_op at /usr/lib/x86_64-linux-gnu/libmpich.so.10 (unknown line)
PMPI_Fetch_and_op at /usr/lib/x86_64-linux-gnu/libmpich.so.10 (unknown line)
mpi_fetch_and_op at /usr/lib/x86_64-linux-gnu/libmpich.so.10 (unknown line)
Fetch_and_op at /home/travis/.julia/v0.6/MPI/src/mpi-base.jl:848
```

Linux openmpi:
```
[ 12%] Building Fortran object CMakeFiles/gen_constants.dir/gen_constants.f90.o
/home/travis/.julia/v0.6/MPI/deps/gen_constants.f90:41.43:
  call output("MPI_NO_OP       ", MPI_NO_OP)
                                           1
Error: Symbol 'mpi_no_op' at (1) has no IMPLICIT type
make[2]: *** [CMakeFiles/gen_constants.dir/gen_constants.f90.o] Error 1
make[1]: *** [CMakeFiles/gen_constants.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by barche** [comment]
Yes, I wasn't exactly happy with the CI results either :)

* The `MPI_NO_OP` is because it doesn't exist yet in OpenMPI 1.x, would it be OK to upgrade to 2.1? That seems to pass on Travis now
* The segfault I don't understand, this passes with mpich 3.2 both on my Arch Linux machine and my Mac, maybe it's a bug in mpich that got fixed between 3.0.x and 3.2?

Note the current iteration still contains some debug output, so it's certainly not ready to merge yet.

**Comment by vchuravy** [comment]
I think upgrading would be fine, but best done in a separate PR though.

**Comment by andreasnoack** [comment]
> maybe it's a bug in mpich that got fixed between 3.0.x and 3.2?

I think that could definitely be the case. I've had issues with the 3.0.x versions of MPICH although they mainly showed up when building with Clang.

**Comment by barche** [comment]
The separate upgrade PR is in #202, I'll rebase this onto master once that is merged. The segfault seems to be indeed due to a fortran bug in MPICH, fixed with the 3.2 release:
http://trac.mpich.org/projects/mpich/ticket/2196

**Comment by barche** [comment]
This is now rebased on master and passes the 0.6 CI.

@tbole I did make a small change to `Info` to make it compatible with passing `MPI.INFO_NULL` to the Window functions, see here:
https://github.com/JuliaParallel/MPI.jl/pull/201/files#diff-fdd46ed6980b3f76213e4503dd40aaf3R109
This is also more consistent with the definition of the other constants in the package.

**Comment by tbole** [comment]
Since you've already added Info and Win C wrappers, would you mind adding [the other wrappers](https://www.open-mpi.org/doc/v2.0/man3/MPI_Info_f2c.3.php) as well? Especially the ones for Requests and Ops should be useful. Otherwise it looks fine to me.

**Comment by barche** [comment]
It's a good idea, but I think it would be better suited for a separate PR, also containing a separate test that checks all the conversions.

**Comment by musm** [comment]
``julia

julia> using MPI
INFO: Precompiling module MPI.
ERROR: LoadError: LoadError: UndefVarError: MPI_NO_OP not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:576
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\Mus\.julia\v0.6\MPI\src\mpi-base.jl, in expression starting on line 87
while loading C:\Users\Mus\.julia\v0.6\MPI\src\MPI.jl, in expression starting on line 18
ERROR: Failed to precompile MPI to C:\Users\Mus\.julia\lib\v0.6\MPI.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
```


I think this is related to this PR. I am on Julia 0.6.2 and am using  MS-MPI v9 .

**Comment by barche** [comment]
Yes, I didn't yet add the Windows constants, mainly because I don't have them handy.

**Comment by musm** [comment]
Anything we could do to fix the precompilation errors?
What kind of information do you need to obtain the Windows constants, I might be able to help you here.

**Comment by tbole** [comment]
You would have to extract that from the MPI include headers. Getting these infos is really hard for non-Windows users. Should be sufficient to search those for MPI_NO_OP. Unfortunately there's no automatic implementation as in Linux.  Since MS-MPI is mostly consistent to MPICH the values are probably identical.

**Comment by barche** [comment]
There are a few more constants in the diff on `gen_constants.f90`:
https://github.com/JuliaParallel/MPI.jl/pull/201/files#diff-a4bac5ebc2dbab5f5516d15268c35c56

They should be in mpi.h, according to a comment in `win_mpiconstants.jl`

**Comment by musm** [comment]
Here's what I found under mpi.h
```c
/*---------------------------------------------------------------------------*/
/* MPI_Op                                                                    */
/*---------------------------------------------------------------------------*/

typedef int MPI_Op;
#define MPI_OP_NULL ((MPI_Op)0x18000000)

#define MPI_MAX     ((MPI_Op)0x58000001)
#define MPI_MIN     ((MPI_Op)0x58000002)
#define MPI_SUM     ((MPI_Op)0x58000003)
#define MPI_PROD    ((MPI_Op)0x58000004)
#define MPI_LAND    ((MPI_Op)0x58000005)
#define MPI_BAND    ((MPI_Op)0x58000006)
#define MPI_LOR     ((MPI_Op)0x58000007)
#define MPI_BOR     ((MPI_Op)0x58000008)
#define MPI_LXOR    ((MPI_Op)0x58000009)
#define MPI_BXOR    ((MPI_Op)0x5800000a)
#define MPI_MINLOC  ((MPI_Op)0x5800000b)
#define MPI_MAXLOC  ((MPI_Op)0x5800000c)
#define MPI_REPLACE ((MPI_Op)0x5800000d)
#define MPI_NO_OP   ((MPI_Op)0x5800000e)
```

**Comment by musm** [comment]
yep
```c
#define MPI_LOCK_EXCLUSIVE  234
#define MPI_LOCK_SHARED     235
#define MPI_INFO_NULL         ((MPI_Info)0x1c000000)
```

**Comment by barche** [comment]
I made a PR, but we'll have to wait for Appveyor to see if it worked. Maybe best to continue the discussion on PR #205 if needed.

**Pull request merged**
