### PR TITLE
support introduction of cookie in master

### LINKED ISSUE #146: MPIManager not working on master
It just hangs. @amitmurthy could this be caused by https://github.com/JuliaLang/julia/pull/16423? I'm on OS X.

### PR DESCRIPTION
**Pull request by amitmurthy**
closes #146

### CODE REVIEW

**Comment by andreasnoack** [comment]
Who or how are these coverage reports controlled? I'd like to avoid the emails. I think the report next to the test results is sufficient.

**Comment by amitmurthy** [comment]
No idea.

**Comment by andreasnoack** [comment]
@amitmurthy This works fine for me. Do you know what is causing the Windows issue?

**Comment by amitmurthy** [comment]
No. But all PRs (open and closed) have failed AV runs in different tests.

I'll merge this for now.

**Comment by eschnett** [comment]
Appveyor isn't set up correctly yet.

We should probably disable it for master, and work on making it work on a branch.

**Pull request merged**
