### PR TITLE
Create docs

### PR DESCRIPTION
**Pull request by simonbyrne**
Moves the documentation from the README file to separate docs.

I don't have commit access, so someone else will need to set up the
registry key.

There are still lots of docstrings missing.

### CODE REVIEW

**Comment by vchuravy** [comment]
Added a DOCUMENTER_KEY

**Comment by simonbyrne** [comment]
Yes, I think so.

**Comment by PhilipVinc** [comment]
Is a link to the docs missing?

**Comment by simonbyrne** [comment]
Yes, I'll add it once I know what it is!

**Comment by simonbyrne** [comment]
Looks like it failed to deploy because the tests are failing. Hopefully should be fixed by #243.

**Pull request merged**
