### PR TITLE
[WIP] Implement MPI_IN_PLACE for MPI Operations

### PR DESCRIPTION
**Pull request by PhilipVinc**
Hi, 

I would like to implement non allocating versions for several MPI operations, as well as MPI_IN_PLACE variants.

This is a first go I had at it at a few functions that I needed, but If you are interested I could go on and gradually do it for other functions. 
I alredy added tests for most of the functions I added. 

For now, I'm hardcoding the value `MPI_IN_PLACE = Ptr{Cvoid}(1)`, taken from `mpi.h` wherever I need it. I believe that there should be a more elegant way to write it.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Failures when running with `mpich` are due to the fact that `MPI_IN_PLACE = (void*)-1` for that implementation, contrary to the `+1` of `openmpi` that I was using for testing.

Could guide me on how to correctly implement the generation of this constant during the build phase, I could fix it? Apparently it's not as trivial as other Integer constants because this is a pointer type.

**Comment by vchuravy** [comment]
I hadn't had time to look into this in detail, but this looks generally good. Why did you close the PR?

**Comment by PhilipVinc** [comment]
Sorry, I closed the PR both because I realized I was pulling from my master branch,  and because I could not reproduce locally one of Travis failures, so I ended up playing with a few commits to understand what was going on.

I'm closing in favor of [#232](https://github.com/JuliaParallel/MPI.jl/pull/232)

**Comment by vchuravy** [comment]
Thanks, that makes sense!

**Pull request closed without merging**
