### PR TITLE
Make OS X tests work in Travis

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by lcw** [comment]
This is cool.  It looks like MacPorts may need to be installed before it is used to install various flavors of MPI, see for example <https://travis-ci.org/JuliaParallel/MPI.jl/jobs/81665959>.

**Comment by eschnett** [comment]
@lcw Thanks for the pointers.

**Comment by eschnett** [comment]
@lcw Is your MacPorts url correct?

**Comment by lcw** [comment]
I am not sure what url you are referring to.

If you want to use MacPorts I think you need to install if first.  See for example this travis file <https://github.com/leanprover/macports/blob/8576f29dafd52659198bc78f92d1f63dd540ea17/.travis.yml>.

**Pull request merged**
