### PR TITLE
Add synchronize to test infrastructure

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@maleadt this has low priority, but I was wondering about allocations, are allocations occuring on a  stream even if `JULIA_CUDA_MEMORY_POOL: "none"`?

**Comment by maleadt** [comment]
> are allocations occuring on a stream even if `JULIA_CUDA_MEMORY_POOL: "none"`?

No, they are not, they are only context-bound and hence are a synchronizing operation wrt. every stream (so it's double bad): https://github.com/JuliaGPU/CUDA.jl/blob/778f7fa21f3f73841a2dada57767e358f80e5997/lib/cudadrv/memory.jl#L86=

**Comment by vchuravy** [comment]
Then I am even more confused why I need to synchronize after allocations :) But it looks like its allocation + copy, should look at this under a profiler to see what's actually happenening

**Comment by maleadt** [comment]
> why I need to synchronize after allocations :) But it looks like its allocation + copy, should look at this under a profiler to see what's actually happenening

You really shouldn't have to. Maybe there's another race that the (delay introduced by the) synchronize resolves?

**Comment by simonbyrne** [comment]
Changes now in #607

**Pull request closed without merging**
