### PR TITLE
deal with vendor=cray but no gtl

### LINKED ISSUE #779: MPIPreferences.use_system_binary(vendor="cray") fails on Piz Daint
```julia
julia> using MPIPreferences

julia> MPIPreferences.use_system_binary(vendor="cray")
ERROR: ArgumentError: Collection is empty, must contain exactly 1 element
Stacktrace:
 [1] only
   @ ./iterators.jl:1517 [inlined]
 [2] cray_mpi(libs::Vector{SubString{String}})
   @ MPIPreferences.CrayParser /scratch/snx3000tds/julia/omlins/daint-gpu/packages/MPIPreferences/43Ix2/src/parse_cray_cc.jl:28
 [3] analyze_cray_cc()
   @ MPIPreferences.CrayParser /scratch/snx3000tds/julia/omlins/daint-gpu/packages/MPIPreferences/43Ix2/src/parse_cray_cc.jl:63
 [4] use_system_binary(; library_names::Vector{String}, mpiexec::String, abi::Nothing, vendor::String, export_prefs::Bool, force::Bool)
   @ MPIPreferences /scratch/snx3000tds/julia/omlins/daint-gpu/packages/MPIPreferences/43Ix2/src/MPIPreferences.jl:175
 [5] top-level scope
   @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by JBlaschke**
Fixes #779 

tagging @marius311 and @omlins

### CODE REVIEW

**Comment by JBlaschke** [comment]
@simonbyrne should I bump the patch version?

**Comment by simonbyrne** [comment]
> @simonbyrne should I bump the patch version?

yes, you should only need to bump MPIPreferences

**Comment by JBlaschke** [comment]
> > @simonbyrne should I bump the patch version?
> 
> yes, you should only need to bump MPIPreferences

Done! Feel free to merge

**Comment by JBlaschke** [comment]
(couldn't resit condensing 4 lines into 1 :wink:  -- I'm done now. I promise.)

**Comment by vchuravy** [comment]
Could we write a test for the writing and parsing of these preference files?

**Comment by JBlaschke** [comment]
@vchuravy do you mean like faking what it would be like on a cray system, by grabbing inputs from perlmutter?

**Comment by giordano** [comment]
> do you mean like faking what it would be like on a cray system, by grabbing inputs from perlmutter?

I'd assume the answer is "yes".

**Pull request merged**
