### PR TITLE
Add tests for isend and some wait/test methods

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by kshyatt** [comment]
Spectacular. The only tests that succeed are on OSX! I'll try to fix this soon.

**Comment by kshyatt** [comment]
I found a bug in `Send` for one-element values that I fixed and added tests for too.

**Comment by kshyatt** [comment]
I think for `Testany!` on MPICH we were missing a case where `flag` can be true, but the `index` can be `MPI_UNDEFINED`. Seems to be working locally on OSX with MPICH for me now.

**Comment by kshyatt** [comment]
The test failure in `bcast` on nightly has nothing to do with this PR - @andreasnoack and @eschnett is this ok to merge?

**Comment by andreasnoack** [comment]
Are you able to reproduce the test error locally? E.g. with `coverage=true` which causes `--inline=no`,

**Comment by kshyatt** [comment]
@andreasnoack yes, the problem is that `Base.copy` can't copy the function `g` in the `bcast` tests.

**Comment by andreasnoack** [comment]
Is it possible to fix that?

**Comment by kshyatt** [comment]
It probably is, but I'm not certain how.

**Comment by kshyatt** [comment]
Success! Ok to merge?

**Comment by andreasnoack** [comment]
Yes. When lights are green.

**Comment by kshyatt** [comment]
Sorry! The AV failure here was actually really important - I fixed a bad test! And I added one last one.

**Comment by kshyatt** [comment]
3/4 AV tests passed (YAY) and the *nix tests are doing well too, so I'm going to merge.

**Pull request merged**
