### PR TITLE
Update CI scripts

### PR DESCRIPTION
**Pull request by simonbyrne**
Run on 1.0 and latest release, use standard Julia Appveyor script and latest Windows MPI (#242).

### CODE REVIEW

**Comment by simonbyrne** [comment]
I'm guessing 32-bit windows is failing because the Windows MPI is 64-bit? Should we just disable the CI for that case?

**Comment by lcw** [comment]
I'm okay with disabling the test.  Although, I don't use Windows MPI.

**Comment by simonbyrne** [comment]
Okay, the 32-bit Windows failure has something to do with this line giving a `Char` when it should be an `Int32` (I think):
https://github.com/JuliaParallel/MPI.jl/blob/bc2e97949aae507414c96c4596961f0d05abc3e5/src/mpi-op.jl#L27

**Comment by simonbyrne** [comment]
That is probably a separate issue. I'll just allow failures for now can figure it out later.

Happy for this to be merged when ready.

**Comment by simonbyrne** [comment]
Alright, now there's a new issue in `test_reduce.jl`:
https://ci.appveyor.com/project/andreasnoack/mpi-jl/builds/24080532/job/qtoh8m4wk64syh3o#L99

**Comment by lcw** [comment]
At this point I saw we merge if all CI passes except 32-bit Windows.

**Comment by simonbyrne** [comment]
I've traced the 32-bit Windows issue to calling `MPI.Reduce!` with user-defined functions. Can't figure out the exact problem though.

**Pull request merged**
