### PR TITLE
Add Sendreccv method

### PR DESCRIPTION
**Pull request by cmcaine**
And some comments.

I haven't added tests or a serialize/deserialize version. Please ask me to add
them or add those yourself if you want them.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Shouldn't this be implemented by calling the underlying MPI_Sendrecv function?

**Comment by cmcaine** [comment]
That looks like a lot more work for a similar result (to me) ;)

The code would need some work to make it actually return error values, but it looks to me like MPI.jl ignores return values for Isend and Irecv anyway?

**Comment by eschnett** [comment]
You can't first send and then receive. If the message is large, and if the sender is the same as the receiver, this would block. Calling `MPI_sendrecv` is the best option to avoid this.

**Comment by PhilipVinc** [comment]
By The way, it’s not much extra work. You need to add one line to `deps/gen_functions.c` Definìning the symbol for `MPI_Sendrecv` and then `ccall ` it with the right signature.

PS: the idea of a wrapper to a library is to wrap the functionality of that library, not to change it (unless there is a valid reason)

**Comment by simonbyrne** [comment]
Closed by #317

**Pull request closed without merging**
