### PR TITLE
remove Char from MPIDatatypes

### PR DESCRIPTION
**Pull request by simonbyrne**
An easy fix to #688.

cc @eschnett @giordano

### CODE REVIEW

**Comment by simonbyrne** [comment]
We now have:
```
julia> using MPI

julia> MPI.Init()
MPI.ThreadLevel(2)

julia> MPI.Datatype(UInt32)
MPI.Datatype(UInt32): MPI_UINT32_T

julia> MPI.Datatype(Char)
MPI.Datatype(Char): Dup MPI_UINT32_T
```

**Comment by giordano** [comment]
Ok, let me try this PR on Ookami again, but I think I was still getting some segfaults when I last tried.

**Comment by giordano** [comment]
Ok, this does solve the crash in `test_allgather`, but then I still run into other segfaults in `test_bcast` and `test_datatypes` (and haven't gone further with this PR), which I had already mentioned in https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341937162 and don't seem to be fixed by removing `Char` from `MPIDatatypes`, so there may be something else, I'd need to track it down.

This PR is probably OK anyway, but perhaps we can add a test like
```julia
all(.!(isempty.(MPI.get_name.(MPI.Datatype.(Base.uniontypes(MPI.MPIDatatype))))))
```
?

Side note, I'm still missing where `MPIDatatype` is used in `MPI.jl/src` :thinking:

**Comment by simonbyrne** [comment]
> Side note, I'm still missing where `MPIDatatype` is used in `MPI.jl/src` 🤔

It isn't. I think it's just a vestige of some earlier code with how we handled datatypes and buffers.

**Comment by giordano** [comment]
But this change does affect `MPI.Datatype(Char)`: https://github.com/JuliaParallel/MPI.jl/pull/689#issuecomment-1347253030

**Comment by simonbyrne** [comment]
> But this change does affect `MPI.Datatype(Char)`: [#689 (comment)](https://github.com/JuliaParallel/MPI.jl/pull/689#issuecomment-1347253030)

Actually it doesn't: I get the same on `master`

**Comment by giordano** [comment]
What MPI are you using?

**Comment by simonbyrne** [comment]
Ah, it was Open MPI.

**Pull request merged**
