### PR TITLE
Fix typo in create_resized

### PR DESCRIPTION
**Pull request by carstenbauer**

### CODE REVIEW

**Comment by carstenbauer** [comment]
@simonbyrne I think this is just a typo, but can you please confirm & merge?

**Comment by simonbyrne** [comment]
Thanks. Any chance you could add a test as well?

**Comment by carstenbauer** [comment]
Done. Added a few tests for the `create_X` functions, including `create_resized`.

**Comment by carstenbauer** [comment]
Apparently adding `StaticArrays.jl` as a test dependency has caused some CI failures. Do you know why that is?

**Comment by carstenbauer** [comment]
Nevermind, I just dropped StaticArrays.jl again. Ready for merge, IMO.

**Comment by simonbyrne** [comment]
Thanks, that's great!

**Pull request merged**
