### PR TITLE
Import constants into `API` instead of creating non-const variables

### PR DESCRIPTION
**Pull request by giordano**
On `master`:
```julia
julia> isconst(MPI.API, :MPI_File)
false
```
with this PR:
```julia
julia> isconst(MPI.API, :MPI_File)
true
```

CC: @t-bltg.

### CODE REVIEW

**Comment by simonbyrne** [comment]
I was actually thinking we should just merge them?

**Comment by giordano** [comment]
Merge what?  The `Consts` and `API` modules?

**Comment by simonbyrne** [comment]
> Merge what? The `Consts` and `API` modules?

Yes. See #650.

**Comment by t-bltg** [comment]
> Merge what? The Consts and API modules?

Yes, @simonbyrne mentioned this in #644, but I couldn't find a way to do this (https://github.com/JuliaParallel/MPI.jl/pull/644#discussion_r982914914).

**Comment by giordano** [comment]
Closing in favour of #650.

**Pull request closed without merging**
