### PR TITLE
[CI] Use Spack OCI build cache for MPI packages

### LINKED ISSUE #744: [CI] Use Spack + OCI buildcache when widely available for system MPI
Ref: https://github.com/haampie/spack-oci-buildcache-example

For example:
```console
mose@Moses-MBP ~ % docker run --rm ghcr.io/haampie/spack-oci-buildcache-example:mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4 mpirun --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
HYDRA build details:
    Version:                                 3.4.3
    Release Date:                            General Availability Release
    CC:                              /home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/lib/spack/env/gcc/gcc
    Configure options:                       '--disable-option-checking' '--prefix=/home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-12.1.0/mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--enable-wrapper-rpath=yes' '--disable-alloca' '--with-pmi=simple' '--enable-fast=all' '--disable-cuda' '--enable-registration-cache' '--with-device=ch4:ofi' 'CC=/home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/lib/spack/env/gcc/gcc' 'CXX=/home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/lib/spack/env/gcc/g++' 'FC=/home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/lib/spack/env/gcc/gfortran' 'F77=/home/runner/work/spack-oci-buildcache-example/spack-oci-buildcache-example/spack/lib/spack/env/gcc/gfortran' '--cache-file=/dev/null' '--srcdir=.' 'CFLAGS= -DNDEBUG -DNVALGRIND -O2' 'LDFLAGS=' 'LIBS=-lm ' 'CPPFLAGS= -DNETMOD_INLINE=__netmod_inline_ofi__ -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/src/mpl/include -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/src/mpl/include -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/modules/yaksa/src/frontend/include -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/modules/yaksa/src/frontend/include -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/modules/json-c -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/modules/json-c -D_REENTRANT -I/tmp/runner/spack-stage/spack-stage-mvapich-3.0b-hoybelw6cwy4n3zdw2hgc3jziwaaisu4/spack-src/src/mpi/romio/include' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select
```

This is very work-in-progress at the moment (https://github.com/spack/spack/pull/38358), but it will save us lots of time to install all various system MPI libraries.

CC: @haampie

### PR DESCRIPTION
**Pull request by giordano**
Fix #744.

### CODE REVIEW

**Comment by haampie** [comment]
dlopen'ed from where? Is julia using runpaths? That can cause rpaths to be ignored when locating dependencies of the library :)

**Comment by giordano** [comment]
dlopen just by name `libmpi` :slightly_smiling_face:

**Comment by giordano** [comment]
Ok, giving a hint of where libmpi is did the trick: https://github.com/JuliaParallel/MPI.jl/pull/788/commits/211c743650ae6c60ae74713f01a38e35677592d4

**Comment by haampie** [comment]
Ah okay, yes, you can set `LD_LIBRARY_PATH` with

```
spack:
  modules:
    prefix_inspections:
      lib: ["LD_LIBRARY_PATH"]
      lib64: ["LD_LIBRARY_PATH"]
```

in the env, and then `spack buildcache push -f` (shouldn't require a rebuild, just a one time --force to create new manifest files that contain env variables).

**Comment by giordano** [comment]
Ok, this is all working well...except GHA is messing up with an environment variable: https://github.com/JuliaParallel/MPI.jl/blob/42e514fe5783e31a85faef155aa59135ac229bfe/.github/workflows/UnitTests.yml#L505-L512 I set `MPITRAMPOLINE_MPIEXEC` to `which mpiexec`, and then try to print it.  https://github.com/JuliaParallel/MPI.jl/actions/runs/6746922493/job/18341922748?pr=788#step:5:23 shows that `MPITRAMPOLINE_MPIEXEC` is set to `/home/runner/work/github-actions-buildcache/github-actions-buildcache/spack/opt/spack/__spack_path_placeholder__/__spack_path_pl/linux-ubuntu22.04-x86_64_v2/gcc-12.3.0/intel-mpi-2019.9.304-ecfipz6mxgepmrkwp5dl5oohion5m54r/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpiexec` (which is the right value), but then when I print its value [I get](https://github.com/JuliaParallel/MPI.jl/actions/runs/6746922493/job/18341922748?pr=788#step:5:26) `/__w/github-actions-buildcache/github-actions-buildcache/spack/opt/spack/__spack_path_placeholder__/__spack_path_pl/linux-ubuntu22.04-x86_64_v2/gcc-12.3.0/intel-mpi-2019.9.304-ecfipz6mxgepmrkwp5dl5oohion5m54r/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpiexec`, which is a non-existing path, basically changing `/home/runner/work` into `/__w`.  No clue why GHA is doing this non-sense.

**Comment by haampie** [comment]
I've updated the paths in the buildcache to `/opt/spack`, which sounds like a more sensible location in general. Fortunately it's writable...

**Comment by giordano** [comment]
Alright, this is working great now!  I'll uncomment all other jobs and then merge.  Thanks @haampie for all the help!

**Comment by giordano** [comment]
Alright, this PR cuts CI time by about 1/3, mainly by bringing the mvapich2 job from 45 minutes to less than 5.  There are still some failures around (some of which tracked by #749), but these are unrelated to this PR.

Thanks @haampie for implementing the OCI caching feature in spack and all the help here! :rocket:

**Pull request merged**
