### PR TITLE
Change function pointers to function prototypes

### LINKED ISSUE #694: Take function prototypes seriously
`MPI_Type_delete_attr_function` is a function prototype, not a function pointer. 

The type of `type_delete_attr_fn` is a function pointer(`MPI_Type_delete_attr_function *`).  `MPI_Type_delete_attr_function` is a function prototype used for declaring this pointer.
```c
int MPI_Type_create_keyval(MPI_Type_copy_attr_function *type_copy_attr_fn,
             MPI_Type_delete_attr_function *type_delete_attr_fn,
             int *type_keyval, void *extra_state)
```

This is the declaration of `MPI_Type_delete_attr_function`:
```c
typedef int MPI_Type_delete_attr_function(MPI_Datatype datatype,
             int type_keyval, void *attribute_val, void *extra_state);
```
which is actually a function prototype and is generally used as a shortcut for declaring pointers.

A function pointer should be declared like this:
```c
typedef int (MPI_Type_delete_attr_function*)(MPI_Datatype datatype,
             int type_keyval, void *attribute_val, void *extra_state);
```

So, the fix in #688 is not right. The root cause is that [these "pointers"](https://github.com/JuliaParallel/MPI.jl/blob/4b9b05f482fb24eab1db2f32352626004b9ebb1c/src/api/mpich.jl#L46-L66) should not be defined as pointers(`Ptr{Cvoid}`).

### PR DESCRIPTION
**Pull request by Gnimuc**
fix #694

### CODE REVIEW

**Comment by giordano** [comment]
Unfortunately this doesn't fix my troubles in #684
```julia
(mvapich) pkg> add https://github.com/Gnimuc/MPI.jl.git#fix-694
     Cloning git-repo `https://github.com/Gnimuc/MPI.jl.git`
    Updating git-repo `https://github.com/Gnimuc/MPI.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/tmp/mvapich/Project.toml`
  [da04e1cc] ~ MPI v0.20.5 `~/.julia/dev/MPI` ⇒ v0.20.5 `https://github.com/Gnimuc/MPI.jl.git#fix-694`
    Updating `~/tmp/mvapich/Manifest.toml`
  [da04e1cc] ~ MPI v0.20.5 `~/.julia/dev/MPI` ⇒ v0.20.5 `https://github.com/Gnimuc/MPI.jl.git#fix-694`
Precompiling environment...
  1 dependency successfully precompiled in 11 seconds. 12 already precompiled.

julia> using MPI

julia> MPI.Init(;threadlevel=:single)
MPI.ThreadLevel(0)

julia> MPI.Datatype(Char)
MPI.Datatype(Char): 

julia> MPI.Finalize()

[1197027] signal (11.1): Segmentation fault
in expression starting at REPL[5]:1
MPIR_Call_attr_delete at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
MPIR_Attr_delete_list at /lustre/software/mvapich2/gcc11/2.3.6/lib/libmpi.so (unknown line)
Allocations: 3851567 (Pool: 3848167; Big: 3400); GC: 7
Segmentation fault (core dumped)
```

**Comment by t-bltg** [comment]
I'm trying to come up with a representative test.

`MPI_Comm_create_errhandler` might be a good candidate.

Porting the example from http://mpi.deino.net/mpi_functions/MPI_Comm_create_errhandler.html to `test/test_errorhandler.jl` shouldn't be too hard, trying that now.

**Comment by Gnimuc** [comment]
The default backend works locally on my machine:

Screenshot 2022-12-19 at 22 56 37

@giordano which backend should I use to reproduce this?

**Comment by giordano** [comment]
All problems I reported in #684 are on [Ookami](https://www.stonybrook.edu/ookami/), most of them with MVAPICH2.  I have no clue how to reproduce them outside of that environment.

**Comment by t-bltg** [comment]
@Gnimuc, you can add the following test to this PR (passes locally on `mpich`):

```diff
diff --git a/test/test_errorhandler.jl b/test/test_errorhandler.jl
index 8bb8fe9e..ba9b8958 100644
--- a/test/test_errorhandler.jl
+++ b/test/test_errorhandler.jl
@@ -8,3 +8,27 @@ MPI.Init()
 MPI.set_errorhandler!(MPI.COMM_SELF, MPI.ERRORS_ARE_FATAL)
 @test MPI.get_errorhandler(MPI.COMM_SELF) == MPI.ERRORS_ARE_FATAL

+# the following is testing function pointers, and is adapted from
+# mpi.deino.net/mpi_functions/MPI_Comm_call_errhandler.html
+
+DUMMY_ERR = MPI.API.MPI_ERR_OTHER[]
+DUMMY_COMM = MPI.API.MPI_COMM_WORLD[]
+
+function error_handler(comm_ptr::Ptr, err_ptr::Ptr)
+    comm = unsafe_load(comm_ptr)
+    err = unsafe_load(err_ptr)
+    @test comm == DUMMY_COMM
+    @test err == DUMMY_ERR
+    nothing
+end
+
+error_handler_c = @cfunction(error_handler, Cvoid, (Ptr{MPI.MPI_Comm}, Ptr{Cint}))
+
+comm = MPI.Comm(DUMMY_COMM)
+errh = MPI.get_errorhandler(comm)
+
+MPI.API.MPI_Comm_create_errhandler(error_handler_c, errh)
+MPI.set_errorhandler!(comm, errh)
+MPI.API.MPI_Comm_call_errhandler(comm, DUMMY_ERR)
+
+MPI.Finalize()
```

**Comment by simonbyrne** [comment]
Thanks for fixing this.

**Pull request merged**
