### PR TITLE
AMDGPU compat

### PR DESCRIPTION
**Pull request by ahojukka5**
Bump compat to latest 0.9 release.

### CODE REVIEW

**Comment by luraess** [comment]
Thanks. Could you also bump the compat in the test ˋProject.toml`?

**Comment by luraess** [comment]
Thanks

**Comment by giordano** [comment]
Tests seem broken in Julia v1.6 now.

**Comment by luraess** [comment]
Seems all good now, except the GPU-aware tests which fails (unrelated to this PR as reported by @giordano). Shall we bump and patch release and take care of the GPU CI in another PR?

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
Did someone confirm that this is fine locally?

**Comment by luraess** [comment]
> Did someone confirm that this is fine locally?

I was in the process but getting stuck as on a cluster under SLURM I did not manage to allocate resources that could be spawned by running MPI test suite from within the test suite... This is a recurring issue one is hitting and I did not find a work-around yet. It would be different on a multi-GPU server node where one could just run `mpiexec` without SLURM with all devices visible, etc...

**Comment by vchuravy** [comment]
@ahojukka5 thank you for your PR. I will close this in favor of #844

**Pull request closed without merging**
