### PR TITLE
Throw more informative error if MPI.Init() is called multiple times

### LINKED ISSUE #309: Issues using MPI.jl in REPL
Is it possible to debug, even a serial, version of a code that contains MPI calls in the REPL?  The issue I'm seeing is that MPI.Init() fails if the code is executed more than once.  See the MWE below:
```
julia> using MPI

julia> MPI.Init()

julia> MPI.Finalize()

julia> MPI.Finalized()
true

julia> MPI.Init()
ERROR: MPI REFCOUNT in incorrect state
Stacktrace:
 [1] Init() at /Users/mowkes/.juliapro/JuliaPro_v1.2.0-1/packages/MPI/RzbIV/src/environment.jl:47
 [2] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #309.

### CODE REVIEW

**Comment by lcw** [comment]
I just tried this in the repl and it seems to work fine!

**Comment by simonbyrne** [comment]
> I just tried this in the repl and it seems to work fine!

What do you mean? That calling `MPI.Init(); MPI.Finalize(); MPI.Init()` worked, or it threw the correct error?

**Comment by lcw** [comment]
> What do you mean? That calling `MPI.Init(); MPI.Finalize(); MPI.Init()` worked, or it threw the correct error?

Sorry to be unclear.  Threw the correct error.  I suggest the change be merged.

**Comment by simonbyrne** [comment]
Cheers, thanks @lcw.

**Pull request merged**
