### PR TITLE
CUDA-aware MPI with tests

### PR DESCRIPTION
**Pull request by simonbyrne**
This incorporates @kose-y's  changes from #286 (squashed) along with tests.

I needed to open a new PR to trigger the Gitlab buildbot.

### CODE REVIEW

**Comment by vchuravy** [comment]
@maleadt can the gitlab-ci cache builds/ccache? We are building MPI from scratch and it would be fantastic if we can speed it up.

**Comment by lcw** [comment]
Thanks @simonbyrne, @simonbyrne, and @kose-y!  Can't wait to try this out.

**Comment by kose-y** [comment]
Thanks, @simonbyrne and @vchuravy! It was a good opportunity for me to look into some of the Julia internals.

**Comment by maleadt** [comment]
@vchuravy for gitlab/ccache, looks like this would be possible with the `cache` keyword: https://gitlab.com/inkscape/inkscape/merge_requests/3/diffs

**Pull request merged**
