### PR TITLE
fix various depwarns under 0.7 (without breaking 0.6)

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request fixes those depwarns under 0.7 that can be fixed without breaking 0.6. Best!

### CODE REVIEW

**Comment by andreasnoack** [comment]
Could you also adjust the CI setup files?

**Comment by Sacha0** [comment]
> Could you also adjust the CI setup files?

Thanks! I nixed the note re. tests failing under 0.5; should I restore that note? Should tests on master be reenabled, or left off? Best!

**Comment by andreasnoack** [comment]
Since this is about 0.7, we better enable testing on master.

**Comment by Sacha0** [comment]
Reenabled AV on master. Best!

**Comment by Sacha0** [comment]
Thanks all!

**Pull request merged**
